name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main # Execute em todo push para a branch 'main'
  workflow_dispatch: # Permite a execução manual na aba Actions

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Use uma versão de Ruby suportada
          bundler-cache: true # Instala dependências do Gemfile

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: jekyll
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
